/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexionntb;

/**
 *
 * @author Usuario
 */
public class PanelRelacional extends javax.swing.JDialog {

    /**
     * Creates new form PanelRelacional
     */
    public PanelRelacional(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new java.awt.GridLayout(10, 1));

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setText("IdProv");
        jPanel1.add(jLabel1);

        jLabel2.setText("IdProd");
        jPanel1.add(jLabel2);

        jLabel3.setText("Nombre producto");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel4.setText(" ");
        jPanel2.add(jLabel4);

        jLabel5.setText(" ");
        jPanel2.add(jLabel5);

        jLabel6.setText("  ");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout());

        jLabel7.setText(" ");
        jPanel3.add(jLabel7);

        jLabel8.setText(" ");
        jPanel3.add(jLabel8);

        jLabel9.setText("  ");
        jPanel3.add(jLabel9);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout());

        jLabel10.setText(" ");
        jPanel4.add(jLabel10);

        jLabel11.setText(" ");
        jPanel4.add(jLabel11);

        jLabel12.setText("  ");
        jPanel4.add(jLabel12);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout());

        jLabel13.setText(" ");
        jPanel5.add(jLabel13);

        jLabel14.setText(" ");
        jPanel5.add(jLabel14);

        jLabel15.setText("  ");
        jPanel5.add(jLabel15);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout());

        jLabel16.setText(" ");
        jPanel6.add(jLabel16);

        jLabel17.setText(" ");
        jPanel6.add(jLabel17);

        jLabel18.setText("  ");
        jPanel6.add(jLabel18);

        getContentPane().add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout());

        jLabel19.setText(" ");
        jPanel7.add(jLabel19);

        jLabel20.setText(" ");
        jPanel7.add(jLabel20);

        jLabel21.setText("  ");
        jPanel7.add(jLabel21);

        getContentPane().add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout());

        jLabel22.setText(" ");
        jPanel8.add(jLabel22);

        jLabel23.setText(" ");
        jPanel8.add(jLabel23);

        jLabel24.setText("  ");
        jPanel8.add(jLabel24);

        getContentPane().add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout());

        jLabel25.setText(" ");
        jPanel9.add(jLabel25);

        jLabel26.setText(" ");
        jPanel9.add(jLabel26);

        jLabel27.setText("  ");
        jPanel9.add(jLabel27);

        getContentPane().add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout());

        jLabel28.setText(" ");
        jPanel10.add(jLabel28);

        jLabel29.setText(" ");
        jPanel10.add(jLabel29);

        jLabel30.setText("  ");
        jPanel10.add(jLabel30);

        getContentPane().add(jPanel10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelRelacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PanelRelacional dialog = new PanelRelacional(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
